#!/run/current-system/profile/bin/bash
# gen-config.sh — emit a self-contained Security Ops OS /etc/config.scm from the
# installer's collected choices.  Uses @@PLACEHOLDER@@ tokens replaced with a
# Guile writer so Scheme special chars ($ in password hashes, \, ") are safe.
# © Cristian Cezar Moisés · sac@securityops.co · AGPL-3.0-or-later
set -Eeuo pipefail
declare -A A
while [ $# -gt 0 ]; do case "$1" in --*) k="${1#--}"; A[$k]="$2"; shift 2;; *) shift;; esac; done
OUT="${A[out]:-/mnt/etc/config.scm}"; mkdir -p "$(dirname "$OUT")"

# Passwords arrive via the environment (SO_UPASS / SO_RPASS), NOT argv — so they
# are never visible in `ps'.  Hash with SHA-512 crypt read from stdin, so a
# passphrase that begins with `-' is not mis-parsed as an openssl option, and the
# plaintext never appears on a command line.  Only the hash is ever written.
UHASH=$(printf '%s' "${SO_UPASS:-}" | openssl passwd -6 -stdin)
RHASH=$(printf '%s' "${SO_RPASS:-}" | openssl passwd -6 -stdin)

# Escape a value destined for a Scheme string literal (backslash first, then "),
# and strip any literal @@ so a free-text value can never collide with a
# substitution token (e.g. a full name typed as "@@UHASH@@").
scm_str(){ printf '%s' "$1" | sed -e 's/@@//g' -e 's/\\/\\\\/g' -e 's/"/\\"/g'; }
# glibc locale source name (codeset stripped): pt_BR.UTF-8 -> pt_BR
LOCALE_SRC="${A[locale]%%.*}"
HOST_E=$(scm_str "${A[host]}"); USER_E=$(scm_str "${A[user]}")
FULLNAME_E=$(scm_str "${A[fullname]}")

# --- per-choice Scheme fragments -------------------------------------------
case "${A[fs]}" in
  ext4)  FSTYPE='"ext4"';  MKMODS='' ;;
  btrfs) FSTYPE='"btrfs"'; MKMODS='"btrfs"' ;;
  xfs)   FSTYPE='"xfs"';   MKMODS='"xfs"' ;;
  zfs)   FSTYPE='"zfs"';   MKMODS='"zfs"' ;;
esac

if [ "${A[encrypt]}" = yes ]; then
  MAPPED="(mapped-devices
   (list (mapped-device
          (source (uuid \"${A[luks-uuid]}\"))
          (target \"cryptroot\")
          (type luks-device-mapping))))"
  ROOTFS="(file-system (mount-point \"/\") (device \"/dev/mapper/cryptroot\")
             (type ${FSTYPE}) (dependencies mapped-devices))"
  # Modules for the default LUKS2 cipher (aes-xts-plain64) so the initrd can
  # unlock root at boot — aes + xts + sha256 (PBKDF hash), plus dm-crypt.
  CRYPTMODS='"dm-crypt" "aes" "xts" "sha256"'
else
  MAPPED=""
  # dce-format UUID (the flavour blkid prints for ext4/btrfs/xfs); default type.
  ROOTFS="(file-system (mount-point \"/\") (device (uuid \"${A[root-uuid]}\")) (type ${FSTYPE}))"
  CRYPTMODS=''
fi

# desktop / WM service + package fragments (all use %desktop-services + a DM)
case "${A[desktop]}" in
  sway) DESKTOP_PKGS='sway swaybg swayidle swaylock waybar foot wofi mako wl-clipboard grim slurp' ;;
  i3)   DESKTOP_PKGS='i3-wm i3status i3lock dmenu xterm xorg-server rofi feh' ;;
  kde)  DESKTOP_PKGS='plasma plasma-desktop konsole dolphin' ;;
esac

XKB=""
[ -n "${A[xkbvariant]}" ] && XKB=" \"${A[xkbvariant]}\""

# --- write the config with @@tokens@@, then substitute via Guile ----------
cat > "${OUT}.tmpl" <<'SCHEME'
;; -*- mode: scheme; -*-
;;; Security Ops OS — generated by security-ops-install
;;; © Cristian Cezar Moisés · sac@securityops.co · AGPL-3.0-or-later
;;; Declarative: keep this file. To rebuild the system after edits, run:
;;;   sudo guix system reconfigure -L /etc/securityos/src /etc/config.scm
;;; (the -L path holds the (securityos …) modules this config imports; the
;;; installer copied that tree to the target for you.)
(use-modules (gnu) (gnu system nss) (gnu system shadow) (gnu system locale)
             (srfi srfi-1)
             (securityos kernel)          ; linux-securityos 7.1.3 (hardened)
             (nongnu packages linux)      ; linux-firmware
             (securityos packages esquema)) ; Esquema container runtime
(use-service-modules base desktop networking ssh sysctl)
(use-package-modules wm xdisorg image image-viewers suckless xorg terminals
                     kde-plasma kde-systemtools password-utils gnupg linux
                     admin networking tor ssh vpn)

;; Define the keyboard layout as a top-level binding: inside an operating-system
;; / bootloader-configuration form the field name `keyboard-layout' shadows the
;; constructor (define-record-type* thunks field values), so referencing a
;; shared %kbd is the only correct way — same pattern as the live config.
(define %kbd (keyboard-layout "@@KEYMAP@@"@@XKB@@))

(operating-system
  (host-name "@@HOST@@")
  (locale "@@LOCALE@@")
  ;; make sure the chosen locale is actually generated (not just referenced)
  (locale-definitions
   (cons (locale-definition (name "@@LOCALE@@") (source "@@LOCALESRC@@"))
         %default-locale-definitions))
  (timezone "@@TZ@@")
  (keyboard-layout %kbd)
  (kernel linux-securityos)
  (firmware (list linux-firmware))
  (initrd-modules (append (list @@MKMODS@@ @@CRYPTMODS@@) %base-initrd-modules))
  (kernel-arguments
   '("quiet" "modprobe.blacklist=pcspkr" "module_blacklist=dccp,sctp,rds,tipc"
     "init_on_alloc=1" "slab_nomerge" "page_alloc.shuffle=1"
     "randomize_kstack_offset=on" "vsyscall=none"
     "random.trust_cpu=on" "preempt=full" "transparent_hugepage=madvise"))

  (bootloader (bootloader-configuration
               (bootloader grub-efi-bootloader)
               (targets (list "/boot/efi"))
               (keyboard-layout %kbd)))
  @@MAPPED@@
  (file-systems
   (cons* @@ROOTFS@@
          (file-system (mount-point "/boot/efi")
                       (device (uuid "@@EFIUUID@@" 'fat32)) (type "vfat"))
          %base-file-systems))

  (users (cons* (user-account
                 (name "@@USER@@") (comment "@@FULLNAME@@")
                 (group "users") (password "@@UHASH@@")
                 (supplementary-groups
                  '("wheel" "netdev" "audio" "video" "input" "lp" "tty"
                    "dialout" "kvm")))
                ;; replace the passwordless base root with our hashed one
                (user-account (name "root") (uid 0) (group "root")
                              (home-directory "/root") (password "@@RHASH@@"))
                (remove (lambda (a) (equal? (user-account-name a) "root"))
                        %base-user-accounts)))

  (packages
   (append
    (list @@DESKTOP_PKGS@@
          keepassxc gnupg firejail nmap wireshark tcpdump tor torsocks
          openssh wireguard-tools openvpn nftables
          esquema)                        ; Security Ops container runtime
    %base-packages))

  (services
   (append
    (list (service openssh-service-type)
          (simple-service 'securityos-sysctl sysctl-service-type
            '(("kernel.kptr_restrict" . "2") ("kernel.dmesg_restrict" . "1")
              ("kernel.yama.ptrace_scope" . "1") ("kernel.randomize_va_space" . "2")
              ("kernel.unprivileged_bpf_disabled" . "1") ("net.core.bpf_jit_harden" . "2")
              ("fs.protected_symlinks" . "1") ("fs.protected_hardlinks" . "1"))))
    (modify-services %desktop-services)))

  ;; root password (hashed)
  (name-service-switch %mdns-host-lookup-nss))
SCHEME

# root password: inject into %base-user-accounts by adding a root override
# (Guix keeps root from %base-user-accounts; set its password via /etc later,
#  or here we rely on `passwd' first boot — but we bake the hash below.)

# Substitute placeholders safely with Guile (handles $, \, " in values).
guile -c '
(use-modules (ice-9 rdelim) (ice-9 regex))
(define (slurp f) (call-with-input-file f (lambda (p) (read-string p))))
(define t (slurp (string-append (cadr (command-line)) ".tmpl")))
(define (sub k v) (set! t (regexp-substitute/global #f (string-append "@@" k "@@") t (quote pre) v (quote post))))
(for-each (lambda (kv) (sub (car kv) (cdr kv)))
  (list (cons "HOST" (list-ref (command-line) 2))
        (cons "LOCALE" (list-ref (command-line) 3))
        (cons "TZ" (list-ref (command-line) 4))
        (cons "KEYMAP" (list-ref (command-line) 5))
        (cons "XKB" (list-ref (command-line) 6))
        (cons "MKMODS" (list-ref (command-line) 7))
        (cons "CRYPTMODS" (list-ref (command-line) 8))
        (cons "MAPPED" (list-ref (command-line) 9))
        (cons "ROOTFS" (list-ref (command-line) 10))
        (cons "EFIUUID" (list-ref (command-line) 11))
        (cons "USER" (list-ref (command-line) 12))
        (cons "FULLNAME" (list-ref (command-line) 13))
        (cons "UHASH" (list-ref (command-line) 14))
        (cons "DESKTOP_PKGS" (list-ref (command-line) 15))
        (cons "RHASH" (list-ref (command-line) 16))
        (cons "LOCALESRC" (list-ref (command-line) 17))))
(call-with-output-file (cadr (command-line)) (lambda (p) (display t p)))
' "$OUT" "$HOST_E" "${A[locale]}" "${A[tz]}" "${A[keymap]}" "$XKB" \
  "$MKMODS" "$CRYPTMODS" "$MAPPED" "$ROOTFS" "${A[efi-uuid]}" \
  "$USER_E" "$FULLNAME_E" "$UHASH" "$DESKTOP_PKGS" "$RHASH" "$LOCALE_SRC"
rm -f "${OUT}.tmpl"
echo "wrote $OUT"
